linters:
  enable: # TODO: enable more linters
    - gocritic
    - unconvert
  settings:
    disabled-checks:
      - ifElseChain
      - elseif

formatters:
  enable: # TODO: switch to gofumpt, gci, goimports.
    - gofmt
