version: "2"

linters:
  default: none
  enable: # TODO: enable more linters
    - gocritic
    - unconvert
  settings:
    gocritic:
      disabled-checks:
        - ifElseChain
        - elseif

formatters:
  enable: # TODO: switch to gofumpt, gci, goimports.
    - gofmt
