# Copyright (c) 2024-2026 Hemi Labs, Inc.
# Use of this source code is governed by the MIT License,
# which can be found in the LICENSE file.

# GitHub Actions workflow to lint, build and test.
name: "Go"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: "go-${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: "${{ github.event_name == 'pull_request' }}"

env:
  # renovate: datasource=github-releases depName=golangci/golangci-lint versioning=semver
  GOLANGCI_LINT_VERSION: "v2.11.3"

permissions:
  contents: read

jobs:
  test:
    name: "Test"
    runs-on: "ubuntu-latest"
    timeout-minutes: 150
    strategy:
      fail-fast: false # if one of these fails, still run the others
      matrix:
        module:
          - eth-trie
          - merkle
          - tss
          - leveldb
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: "Setup Go"
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: "${{ matrix.module }}/go.mod"

      - name: "Download dependencies"
        working-directory: "${{ matrix.module }}"
        run: go mod download && go mod verify

      - name: "go test"
        if: matrix.module != 'leveldb'
        working-directory: "${{ matrix.module }}"
        run: go test -tags tssexamples -timeout 120m -v -cover ./...

      - name: "go test (short)"
        if: matrix.module == 'leveldb'
        working-directory: "${{ matrix.module }}"
        run: go test -short -timeout 1h ./...

      - name: "go test (leveldb)"
        if: matrix.module == 'leveldb'
        working-directory: "${{ matrix.module }}"
        run: go test -timeout 30m -race -run "TestDB_(Concurrent|GoleveldbIssue74)" ./leveldb

  lint:
    name: "Lint"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        module:
          - tss
          - leveldb
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: "Setup Go"
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: "${{ matrix.module }}/go.mod"

      - name: "golangci-lint"
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          working-directory: "${{ matrix.module }}"
          version: "${{ env.GOLANGCI_LINT_VERSION }}"

      - name: "golangci-lint fmt"
        working-directory: "${{ matrix.module }}"
        run: golangci-lint fmt --diff ./...
